[package]
name = "rgb"
version = "0.1.0"
authors = ["Samuel Gosselin <gosselin.sam@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "~2.27.0"
tui = "0.14"
termion = "1.5"
