use std::fmt;

/// Represents an opcode for the LR35902 CPU.
#[derive(Debug)]
pub struct Opcode {
    pub is_cb: bool,
    pub value: u8,
    pub ncycles: (usize, usize),
    pub mnemo: &'static str,
}

// NOTE: decoding opcodes
//
// This implementation follows this guide for decoding opcodes:
// https://bit.ly/36rAZac. The (p, q, x, y, z) attributes of an
// opcode are defined in the article. As such, it is recommended
// to follow the article when modifying the functions below.
//
impl Opcode {
    pub fn from(is_cb: bool, value: u8) -> Option<&'static Opcode> {
        return if is_cb {
            TABLE_CB_PREFIXED[value as usize].as_ref()
        } else {
            TABLE_UN_PREFIXED[value as usize].as_ref()
        };
    }

    pub fn x(&self) -> u8 { (self.value & 0b1100_0000) >> 6 }
    pub fn y(&self) -> u8 { (self.value & 0b0011_1000) >> 3 }
    pub fn z(&self) -> u8 { self.value & 0b0000_0111 }
    pub fn p(&self) -> u8 { (self.value & 0b0011_0000) >> 4 }
    pub fn q(&self) -> u8 { (self.value & 0b0000_1000) >> 3 }
}

impl fmt::Display for Opcode {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "opcode( is_cb:{}", if self.is_cb { "T" } else { "F" });
        write!(f, ", value=0x{:02x}", self.value);
        write!(f, ", ncycles=({:2},{:2})", self.ncycles.0, self.ncycles.1);
        write!(f, ", mnemo='{:10}'", self.mnemo);
        write!(f, " )")
    }
}

// =======================================================================
// NOTE: the tables below are auto-generated; please do not edit manually.
// =======================================================================

// Table that contains un-prefixed opcodes.
pub const TABLE_UN_PREFIXED: [Option<Opcode>; 256] = [
	Some( Opcode { is_cb: false, value: 0x00, ncycles: ( 4,  4), mnemo: "NOP" } ),
	Some( Opcode { is_cb: false, value: 0x01, ncycles: (12, 12), mnemo: "LD BC,d16" } ),
	Some( Opcode { is_cb: false, value: 0x02, ncycles: ( 8,  8), mnemo: "LD (BC),A" } ),
	Some( Opcode { is_cb: false, value: 0x03, ncycles: ( 8,  8), mnemo: "INC BC" } ),
	Some( Opcode { is_cb: false, value: 0x04, ncycles: ( 4,  4), mnemo: "INC B" } ),
	Some( Opcode { is_cb: false, value: 0x05, ncycles: ( 4,  4), mnemo: "DEC B" } ),
	Some( Opcode { is_cb: false, value: 0x06, ncycles: ( 8,  8), mnemo: "LD B,d8" } ),
	Some( Opcode { is_cb: false, value: 0x07, ncycles: ( 4,  4), mnemo: "RLCA" } ),
	Some( Opcode { is_cb: false, value: 0x08, ncycles: (20, 20), mnemo: "LD (a16),SP" } ),
	Some( Opcode { is_cb: false, value: 0x09, ncycles: ( 8,  8), mnemo: "ADD HL,BC" } ),
	Some( Opcode { is_cb: false, value: 0x0a, ncycles: ( 8,  8), mnemo: "LD A,(BC)" } ),
	Some( Opcode { is_cb: false, value: 0x0b, ncycles: ( 8,  8), mnemo: "DEC BC" } ),
	Some( Opcode { is_cb: false, value: 0x0c, ncycles: ( 4,  4), mnemo: "INC C" } ),
	Some( Opcode { is_cb: false, value: 0x0d, ncycles: ( 4,  4), mnemo: "DEC C" } ),
	Some( Opcode { is_cb: false, value: 0x0e, ncycles: ( 8,  8), mnemo: "LD C,d8" } ),
	Some( Opcode { is_cb: false, value: 0x0f, ncycles: ( 4,  4), mnemo: "RRCA" } ),
	Some( Opcode { is_cb: false, value: 0x10, ncycles: ( 4,  4), mnemo: "STOP 0" } ),
	Some( Opcode { is_cb: false, value: 0x11, ncycles: (12, 12), mnemo: "LD DE,d16" } ),
	Some( Opcode { is_cb: false, value: 0x12, ncycles: ( 8,  8), mnemo: "LD (DE),A" } ),
	Some( Opcode { is_cb: false, value: 0x13, ncycles: ( 8,  8), mnemo: "INC DE" } ),
	Some( Opcode { is_cb: false, value: 0x14, ncycles: ( 4,  4), mnemo: "INC D" } ),
	Some( Opcode { is_cb: false, value: 0x15, ncycles: ( 4,  4), mnemo: "DEC D" } ),
	Some( Opcode { is_cb: false, value: 0x16, ncycles: ( 8,  8), mnemo: "LD D,d8" } ),
	Some( Opcode { is_cb: false, value: 0x17, ncycles: ( 4,  4), mnemo: "RLA" } ),
	Some( Opcode { is_cb: false, value: 0x18, ncycles: (12, 12), mnemo: "JR r8" } ),
	Some( Opcode { is_cb: false, value: 0x19, ncycles: ( 8,  8), mnemo: "ADD HL,DE" } ),
	Some( Opcode { is_cb: false, value: 0x1a, ncycles: ( 8,  8), mnemo: "LD A,(DE)" } ),
	Some( Opcode { is_cb: false, value: 0x1b, ncycles: ( 8,  8), mnemo: "DEC DE" } ),
	Some( Opcode { is_cb: false, value: 0x1c, ncycles: ( 4,  4), mnemo: "INC E" } ),
	Some( Opcode { is_cb: false, value: 0x1d, ncycles: ( 4,  4), mnemo: "DEC E" } ),
	Some( Opcode { is_cb: false, value: 0x1e, ncycles: ( 8,  8), mnemo: "LD E,d8" } ),
	Some( Opcode { is_cb: false, value: 0x1f, ncycles: ( 4,  4), mnemo: "RRA" } ),
	Some( Opcode { is_cb: false, value: 0x20, ncycles: (12,  8), mnemo: "JR NZ,r8" } ),
	Some( Opcode { is_cb: false, value: 0x21, ncycles: (12, 12), mnemo: "LD HL,d16" } ),
	Some( Opcode { is_cb: false, value: 0x22, ncycles: ( 8,  8), mnemo: "LD (HL+),A" } ),
	Some( Opcode { is_cb: false, value: 0x23, ncycles: ( 8,  8), mnemo: "INC HL" } ),
	Some( Opcode { is_cb: false, value: 0x24, ncycles: ( 4,  4), mnemo: "INC H" } ),
	Some( Opcode { is_cb: false, value: 0x25, ncycles: ( 4,  4), mnemo: "DEC H" } ),
	Some( Opcode { is_cb: false, value: 0x26, ncycles: ( 8,  8), mnemo: "LD H,d8" } ),
	Some( Opcode { is_cb: false, value: 0x27, ncycles: ( 4,  4), mnemo: "DAA" } ),
	Some( Opcode { is_cb: false, value: 0x28, ncycles: (12,  8), mnemo: "JR Z,r8" } ),
	Some( Opcode { is_cb: false, value: 0x29, ncycles: ( 8,  8), mnemo: "ADD HL,HL" } ),
	Some( Opcode { is_cb: false, value: 0x2a, ncycles: ( 8,  8), mnemo: "LD A,(HL+)" } ),
	Some( Opcode { is_cb: false, value: 0x2b, ncycles: ( 8,  8), mnemo: "DEC HL" } ),
	Some( Opcode { is_cb: false, value: 0x2c, ncycles: ( 4,  4), mnemo: "INC L" } ),
	Some( Opcode { is_cb: false, value: 0x2d, ncycles: ( 4,  4), mnemo: "DEC L" } ),
	Some( Opcode { is_cb: false, value: 0x2e, ncycles: ( 8,  8), mnemo: "LD L,d8" } ),
	Some( Opcode { is_cb: false, value: 0x2f, ncycles: ( 4,  4), mnemo: "CPL" } ),
	Some( Opcode { is_cb: false, value: 0x30, ncycles: (12,  8), mnemo: "JR NC,r8" } ),
	Some( Opcode { is_cb: false, value: 0x31, ncycles: (12, 12), mnemo: "LD SP,d16" } ),
	Some( Opcode { is_cb: false, value: 0x32, ncycles: ( 8,  8), mnemo: "LD (HL-),A" } ),
	Some( Opcode { is_cb: false, value: 0x33, ncycles: ( 8,  8), mnemo: "INC SP" } ),
	Some( Opcode { is_cb: false, value: 0x34, ncycles: (12, 12), mnemo: "INC (HL)" } ),
	Some( Opcode { is_cb: false, value: 0x35, ncycles: (12, 12), mnemo: "DEC (HL)" } ),
	Some( Opcode { is_cb: false, value: 0x36, ncycles: (12, 12), mnemo: "LD (HL),d8" } ),
	Some( Opcode { is_cb: false, value: 0x37, ncycles: ( 4,  4), mnemo: "SCF" } ),
	Some( Opcode { is_cb: false, value: 0x38, ncycles: (12,  8), mnemo: "JR C,r8" } ),
	Some( Opcode { is_cb: false, value: 0x39, ncycles: ( 8,  8), mnemo: "ADD HL,SP" } ),
	Some( Opcode { is_cb: false, value: 0x3a, ncycles: ( 8,  8), mnemo: "LD A,(HL-)" } ),
	Some( Opcode { is_cb: false, value: 0x3b, ncycles: ( 8,  8), mnemo: "DEC SP" } ),
	Some( Opcode { is_cb: false, value: 0x3c, ncycles: ( 4,  4), mnemo: "INC A" } ),
	Some( Opcode { is_cb: false, value: 0x3d, ncycles: ( 4,  4), mnemo: "DEC A" } ),
	Some( Opcode { is_cb: false, value: 0x3e, ncycles: ( 8,  8), mnemo: "LD A,d8" } ),
	Some( Opcode { is_cb: false, value: 0x3f, ncycles: ( 4,  4), mnemo: "CCF" } ),
	Some( Opcode { is_cb: false, value: 0x40, ncycles: ( 4,  4), mnemo: "LD B,B" } ),
	Some( Opcode { is_cb: false, value: 0x41, ncycles: ( 4,  4), mnemo: "LD B,C" } ),
	Some( Opcode { is_cb: false, value: 0x42, ncycles: ( 4,  4), mnemo: "LD B,D" } ),
	Some( Opcode { is_cb: false, value: 0x43, ncycles: ( 4,  4), mnemo: "LD B,E" } ),
	Some( Opcode { is_cb: false, value: 0x44, ncycles: ( 4,  4), mnemo: "LD B,H" } ),
	Some( Opcode { is_cb: false, value: 0x45, ncycles: ( 4,  4), mnemo: "LD B,L" } ),
	Some( Opcode { is_cb: false, value: 0x46, ncycles: ( 8,  8), mnemo: "LD B,(HL)" } ),
	Some( Opcode { is_cb: false, value: 0x47, ncycles: ( 4,  4), mnemo: "LD B,A" } ),
	Some( Opcode { is_cb: false, value: 0x48, ncycles: ( 4,  4), mnemo: "LD C,B" } ),
	Some( Opcode { is_cb: false, value: 0x49, ncycles: ( 4,  4), mnemo: "LD C,C" } ),
	Some( Opcode { is_cb: false, value: 0x4a, ncycles: ( 4,  4), mnemo: "LD C,D" } ),
	Some( Opcode { is_cb: false, value: 0x4b, ncycles: ( 4,  4), mnemo: "LD C,E" } ),
	Some( Opcode { is_cb: false, value: 0x4c, ncycles: ( 4,  4), mnemo: "LD C,H" } ),
	Some( Opcode { is_cb: false, value: 0x4d, ncycles: ( 4,  4), mnemo: "LD C,L" } ),
	Some( Opcode { is_cb: false, value: 0x4e, ncycles: ( 8,  8), mnemo: "LD C,(HL)" } ),
	Some( Opcode { is_cb: false, value: 0x4f, ncycles: ( 4,  4), mnemo: "LD C,A" } ),
	Some( Opcode { is_cb: false, value: 0x50, ncycles: ( 4,  4), mnemo: "LD D,B" } ),
	Some( Opcode { is_cb: false, value: 0x51, ncycles: ( 4,  4), mnemo: "LD D,C" } ),
	Some( Opcode { is_cb: false, value: 0x52, ncycles: ( 4,  4), mnemo: "LD D,D" } ),
	Some( Opcode { is_cb: false, value: 0x53, ncycles: ( 4,  4), mnemo: "LD D,E" } ),
	Some( Opcode { is_cb: false, value: 0x54, ncycles: ( 4,  4), mnemo: "LD D,H" } ),
	Some( Opcode { is_cb: false, value: 0x55, ncycles: ( 4,  4), mnemo: "LD D,L" } ),
	Some( Opcode { is_cb: false, value: 0x56, ncycles: ( 8,  8), mnemo: "LD D,(HL)" } ),
	Some( Opcode { is_cb: false, value: 0x57, ncycles: ( 4,  4), mnemo: "LD D,A" } ),
	Some( Opcode { is_cb: false, value: 0x58, ncycles: ( 4,  4), mnemo: "LD E,B" } ),
	Some( Opcode { is_cb: false, value: 0x59, ncycles: ( 4,  4), mnemo: "LD E,C" } ),
	Some( Opcode { is_cb: false, value: 0x5a, ncycles: ( 4,  4), mnemo: "LD E,D" } ),
	Some( Opcode { is_cb: false, value: 0x5b, ncycles: ( 4,  4), mnemo: "LD E,E" } ),
	Some( Opcode { is_cb: false, value: 0x5c, ncycles: ( 4,  4), mnemo: "LD E,H" } ),
	Some( Opcode { is_cb: false, value: 0x5d, ncycles: ( 4,  4), mnemo: "LD E,L" } ),
	Some( Opcode { is_cb: false, value: 0x5e, ncycles: ( 8,  8), mnemo: "LD E,(HL)" } ),
	Some( Opcode { is_cb: false, value: 0x5f, ncycles: ( 4,  4), mnemo: "LD E,A" } ),
	Some( Opcode { is_cb: false, value: 0x60, ncycles: ( 4,  4), mnemo: "LD H,B" } ),
	Some( Opcode { is_cb: false, value: 0x61, ncycles: ( 4,  4), mnemo: "LD H,C" } ),
	Some( Opcode { is_cb: false, value: 0x62, ncycles: ( 4,  4), mnemo: "LD H,D" } ),
	Some( Opcode { is_cb: false, value: 0x63, ncycles: ( 4,  4), mnemo: "LD H,E" } ),
	Some( Opcode { is_cb: false, value: 0x64, ncycles: ( 4,  4), mnemo: "LD H,H" } ),
	Some( Opcode { is_cb: false, value: 0x65, ncycles: ( 4,  4), mnemo: "LD H,L" } ),
	Some( Opcode { is_cb: false, value: 0x66, ncycles: ( 8,  8), mnemo: "LD H,(HL)" } ),
	Some( Opcode { is_cb: false, value: 0x67, ncycles: ( 4,  4), mnemo: "LD H,A" } ),
	Some( Opcode { is_cb: false, value: 0x68, ncycles: ( 4,  4), mnemo: "LD L,B" } ),
	Some( Opcode { is_cb: false, value: 0x69, ncycles: ( 4,  4), mnemo: "LD L,C" } ),
	Some( Opcode { is_cb: false, value: 0x6a, ncycles: ( 4,  4), mnemo: "LD L,D" } ),
	Some( Opcode { is_cb: false, value: 0x6b, ncycles: ( 4,  4), mnemo: "LD L,E" } ),
	Some( Opcode { is_cb: false, value: 0x6c, ncycles: ( 4,  4), mnemo: "LD L,H" } ),
	Some( Opcode { is_cb: false, value: 0x6d, ncycles: ( 4,  4), mnemo: "LD L,L" } ),
	Some( Opcode { is_cb: false, value: 0x6e, ncycles: ( 8,  8), mnemo: "LD L,(HL)" } ),
	Some( Opcode { is_cb: false, value: 0x6f, ncycles: ( 4,  4), mnemo: "LD L,A" } ),
	Some( Opcode { is_cb: false, value: 0x70, ncycles: ( 8,  8), mnemo: "LD (HL),B" } ),
	Some( Opcode { is_cb: false, value: 0x71, ncycles: ( 8,  8), mnemo: "LD (HL),C" } ),
	Some( Opcode { is_cb: false, value: 0x72, ncycles: ( 8,  8), mnemo: "LD (HL),D" } ),
	Some( Opcode { is_cb: false, value: 0x73, ncycles: ( 8,  8), mnemo: "LD (HL),E" } ),
	Some( Opcode { is_cb: false, value: 0x74, ncycles: ( 8,  8), mnemo: "LD (HL),H" } ),
	Some( Opcode { is_cb: false, value: 0x75, ncycles: ( 8,  8), mnemo: "LD (HL),L" } ),
	Some( Opcode { is_cb: false, value: 0x76, ncycles: ( 4,  4), mnemo: "HALT" } ),
	Some( Opcode { is_cb: false, value: 0x77, ncycles: ( 8,  8), mnemo: "LD (HL),A" } ),
	Some( Opcode { is_cb: false, value: 0x78, ncycles: ( 4,  4), mnemo: "LD A,B" } ),
	Some( Opcode { is_cb: false, value: 0x79, ncycles: ( 4,  4), mnemo: "LD A,C" } ),
	Some( Opcode { is_cb: false, value: 0x7a, ncycles: ( 4,  4), mnemo: "LD A,D" } ),
	Some( Opcode { is_cb: false, value: 0x7b, ncycles: ( 4,  4), mnemo: "LD A,E" } ),
	Some( Opcode { is_cb: false, value: 0x7c, ncycles: ( 4,  4), mnemo: "LD A,H" } ),
	Some( Opcode { is_cb: false, value: 0x7d, ncycles: ( 4,  4), mnemo: "LD A,L" } ),
	Some( Opcode { is_cb: false, value: 0x7e, ncycles: ( 8,  8), mnemo: "LD A,(HL)" } ),
	Some( Opcode { is_cb: false, value: 0x7f, ncycles: ( 4,  4), mnemo: "LD A,A" } ),
	Some( Opcode { is_cb: false, value: 0x80, ncycles: ( 4,  4), mnemo: "ADD A,B" } ),
	Some( Opcode { is_cb: false, value: 0x81, ncycles: ( 4,  4), mnemo: "ADD A,C" } ),
	Some( Opcode { is_cb: false, value: 0x82, ncycles: ( 4,  4), mnemo: "ADD A,D" } ),
	Some( Opcode { is_cb: false, value: 0x83, ncycles: ( 4,  4), mnemo: "ADD A,E" } ),
	Some( Opcode { is_cb: false, value: 0x84, ncycles: ( 4,  4), mnemo: "ADD A,H" } ),
	Some( Opcode { is_cb: false, value: 0x85, ncycles: ( 4,  4), mnemo: "ADD A,L" } ),
	Some( Opcode { is_cb: false, value: 0x86, ncycles: ( 8,  8), mnemo: "ADD A,(HL)" } ),
	Some( Opcode { is_cb: false, value: 0x87, ncycles: ( 4,  4), mnemo: "ADD A,A" } ),
	Some( Opcode { is_cb: false, value: 0x88, ncycles: ( 4,  4), mnemo: "ADC A,B" } ),
	Some( Opcode { is_cb: false, value: 0x89, ncycles: ( 4,  4), mnemo: "ADC A,C" } ),
	Some( Opcode { is_cb: false, value: 0x8a, ncycles: ( 4,  4), mnemo: "ADC A,D" } ),
	Some( Opcode { is_cb: false, value: 0x8b, ncycles: ( 4,  4), mnemo: "ADC A,E" } ),
	Some( Opcode { is_cb: false, value: 0x8c, ncycles: ( 4,  4), mnemo: "ADC A,H" } ),
	Some( Opcode { is_cb: false, value: 0x8d, ncycles: ( 4,  4), mnemo: "ADC A,L" } ),
	Some( Opcode { is_cb: false, value: 0x8e, ncycles: ( 8,  8), mnemo: "ADC A,(HL)" } ),
	Some( Opcode { is_cb: false, value: 0x8f, ncycles: ( 4,  4), mnemo: "ADC A,A" } ),
	Some( Opcode { is_cb: false, value: 0x90, ncycles: ( 4,  4), mnemo: "SUB B" } ),
	Some( Opcode { is_cb: false, value: 0x91, ncycles: ( 4,  4), mnemo: "SUB C" } ),
	Some( Opcode { is_cb: false, value: 0x92, ncycles: ( 4,  4), mnemo: "SUB D" } ),
	Some( Opcode { is_cb: false, value: 0x93, ncycles: ( 4,  4), mnemo: "SUB E" } ),
	Some( Opcode { is_cb: false, value: 0x94, ncycles: ( 4,  4), mnemo: "SUB H" } ),
	Some( Opcode { is_cb: false, value: 0x95, ncycles: ( 4,  4), mnemo: "SUB L" } ),
	Some( Opcode { is_cb: false, value: 0x96, ncycles: ( 8,  8), mnemo: "SUB (HL)" } ),
	Some( Opcode { is_cb: false, value: 0x97, ncycles: ( 4,  4), mnemo: "SUB A" } ),
	Some( Opcode { is_cb: false, value: 0x98, ncycles: ( 4,  4), mnemo: "SBC A,B" } ),
	Some( Opcode { is_cb: false, value: 0x99, ncycles: ( 4,  4), mnemo: "SBC A,C" } ),
	Some( Opcode { is_cb: false, value: 0x9a, ncycles: ( 4,  4), mnemo: "SBC A,D" } ),
	Some( Opcode { is_cb: false, value: 0x9b, ncycles: ( 4,  4), mnemo: "SBC A,E" } ),
	Some( Opcode { is_cb: false, value: 0x9c, ncycles: ( 4,  4), mnemo: "SBC A,H" } ),
	Some( Opcode { is_cb: false, value: 0x9d, ncycles: ( 4,  4), mnemo: "SBC A,L" } ),
	Some( Opcode { is_cb: false, value: 0x9e, ncycles: ( 8,  8), mnemo: "SBC A,(HL)" } ),
	Some( Opcode { is_cb: false, value: 0x9f, ncycles: ( 4,  4), mnemo: "SBC A,A" } ),
	Some( Opcode { is_cb: false, value: 0xa0, ncycles: ( 4,  4), mnemo: "AND B" } ),
	Some( Opcode { is_cb: false, value: 0xa1, ncycles: ( 4,  4), mnemo: "AND C" } ),
	Some( Opcode { is_cb: false, value: 0xa2, ncycles: ( 4,  4), mnemo: "AND D" } ),
	Some( Opcode { is_cb: false, value: 0xa3, ncycles: ( 4,  4), mnemo: "AND E" } ),
	Some( Opcode { is_cb: false, value: 0xa4, ncycles: ( 4,  4), mnemo: "AND H" } ),
	Some( Opcode { is_cb: false, value: 0xa5, ncycles: ( 4,  4), mnemo: "AND L" } ),
	Some( Opcode { is_cb: false, value: 0xa6, ncycles: ( 8,  8), mnemo: "AND (HL)" } ),
	Some( Opcode { is_cb: false, value: 0xa7, ncycles: ( 4,  4), mnemo: "AND A" } ),
	Some( Opcode { is_cb: false, value: 0xa8, ncycles: ( 4,  4), mnemo: "XOR B" } ),
	Some( Opcode { is_cb: false, value: 0xa9, ncycles: ( 4,  4), mnemo: "XOR C" } ),
	Some( Opcode { is_cb: false, value: 0xaa, ncycles: ( 4,  4), mnemo: "XOR D" } ),
	Some( Opcode { is_cb: false, value: 0xab, ncycles: ( 4,  4), mnemo: "XOR E" } ),
	Some( Opcode { is_cb: false, value: 0xac, ncycles: ( 4,  4), mnemo: "XOR H" } ),
	Some( Opcode { is_cb: false, value: 0xad, ncycles: ( 4,  4), mnemo: "XOR L" } ),
	Some( Opcode { is_cb: false, value: 0xae, ncycles: ( 8,  8), mnemo: "XOR (HL)" } ),
	Some( Opcode { is_cb: false, value: 0xaf, ncycles: ( 4,  4), mnemo: "XOR A" } ),
	Some( Opcode { is_cb: false, value: 0xb0, ncycles: ( 4,  4), mnemo: "OR B" } ),
	Some( Opcode { is_cb: false, value: 0xb1, ncycles: ( 4,  4), mnemo: "OR C" } ),
	Some( Opcode { is_cb: false, value: 0xb2, ncycles: ( 4,  4), mnemo: "OR D" } ),
	Some( Opcode { is_cb: false, value: 0xb3, ncycles: ( 4,  4), mnemo: "OR E" } ),
	Some( Opcode { is_cb: false, value: 0xb4, ncycles: ( 4,  4), mnemo: "OR H" } ),
	Some( Opcode { is_cb: false, value: 0xb5, ncycles: ( 4,  4), mnemo: "OR L" } ),
	Some( Opcode { is_cb: false, value: 0xb6, ncycles: ( 8,  8), mnemo: "OR (HL)" } ),
	Some( Opcode { is_cb: false, value: 0xb7, ncycles: ( 4,  4), mnemo: "OR A" } ),
	Some( Opcode { is_cb: false, value: 0xb8, ncycles: ( 4,  4), mnemo: "CP B" } ),
	Some( Opcode { is_cb: false, value: 0xb9, ncycles: ( 4,  4), mnemo: "CP C" } ),
	Some( Opcode { is_cb: false, value: 0xba, ncycles: ( 4,  4), mnemo: "CP D" } ),
	Some( Opcode { is_cb: false, value: 0xbb, ncycles: ( 4,  4), mnemo: "CP E" } ),
	Some( Opcode { is_cb: false, value: 0xbc, ncycles: ( 4,  4), mnemo: "CP H" } ),
	Some( Opcode { is_cb: false, value: 0xbd, ncycles: ( 4,  4), mnemo: "CP L" } ),
	Some( Opcode { is_cb: false, value: 0xbe, ncycles: ( 8,  8), mnemo: "CP (HL)" } ),
	Some( Opcode { is_cb: false, value: 0xbf, ncycles: ( 4,  4), mnemo: "CP A" } ),
	Some( Opcode { is_cb: false, value: 0xc0, ncycles: (20,  8), mnemo: "RET NZ" } ),
	Some( Opcode { is_cb: false, value: 0xc1, ncycles: (12, 12), mnemo: "POP BC" } ),
	Some( Opcode { is_cb: false, value: 0xc2, ncycles: (16, 12), mnemo: "JP NZ,a16" } ),
	Some( Opcode { is_cb: false, value: 0xc3, ncycles: (16, 16), mnemo: "JP a16" } ),
	Some( Opcode { is_cb: false, value: 0xc4, ncycles: (24, 12), mnemo: "CALL NZ,a16" } ),
	Some( Opcode { is_cb: false, value: 0xc5, ncycles: (16, 16), mnemo: "PUSH BC" } ),
	Some( Opcode { is_cb: false, value: 0xc6, ncycles: ( 8,  8), mnemo: "ADD A,d8" } ),
	Some( Opcode { is_cb: false, value: 0xc7, ncycles: (16, 16), mnemo: "RST 00H" } ),
	Some( Opcode { is_cb: false, value: 0xc8, ncycles: (20,  8), mnemo: "RET Z" } ),
	Some( Opcode { is_cb: false, value: 0xc9, ncycles: (16, 16), mnemo: "RET" } ),
	Some( Opcode { is_cb: false, value: 0xca, ncycles: (16, 12), mnemo: "JP Z,a16" } ),
	Some( Opcode { is_cb: false, value: 0xcb, ncycles: ( 4,  4), mnemo: "PREFIX CB" } ),
	Some( Opcode { is_cb: false, value: 0xcc, ncycles: (24, 12), mnemo: "CALL Z,a16" } ),
	Some( Opcode { is_cb: false, value: 0xcd, ncycles: (24, 24), mnemo: "CALL a16" } ),
	Some( Opcode { is_cb: false, value: 0xce, ncycles: ( 8,  8), mnemo: "ADC A,d8" } ),
	Some( Opcode { is_cb: false, value: 0xcf, ncycles: (16, 16), mnemo: "RST 08H" } ),
	Some( Opcode { is_cb: false, value: 0xd0, ncycles: (20,  8), mnemo: "RET NC" } ),
	Some( Opcode { is_cb: false, value: 0xd1, ncycles: (12, 12), mnemo: "POP DE" } ),
	Some( Opcode { is_cb: false, value: 0xd2, ncycles: (16, 12), mnemo: "JP NC,a16" } ),
	None, // 0xd3
	Some( Opcode { is_cb: false, value: 0xd4, ncycles: (24, 12), mnemo: "CALL NC,a16" } ),
	Some( Opcode { is_cb: false, value: 0xd5, ncycles: (16, 16), mnemo: "PUSH DE" } ),
	Some( Opcode { is_cb: false, value: 0xd6, ncycles: ( 8,  8), mnemo: "SUB d8" } ),
	Some( Opcode { is_cb: false, value: 0xd7, ncycles: (16, 16), mnemo: "RST 10H" } ),
	Some( Opcode { is_cb: false, value: 0xd8, ncycles: (20,  8), mnemo: "RET C" } ),
	Some( Opcode { is_cb: false, value: 0xd9, ncycles: (16, 16), mnemo: "RETI" } ),
	Some( Opcode { is_cb: false, value: 0xda, ncycles: (16, 12), mnemo: "JP C,a16" } ),
	None, // 0xdb
	Some( Opcode { is_cb: false, value: 0xdc, ncycles: (24, 12), mnemo: "CALL C,a16" } ),
	None, // 0xdd
	Some( Opcode { is_cb: false, value: 0xde, ncycles: ( 8,  8), mnemo: "SBC A,d8" } ),
	Some( Opcode { is_cb: false, value: 0xdf, ncycles: (16, 16), mnemo: "RST 18H" } ),
	Some( Opcode { is_cb: false, value: 0xe0, ncycles: (12, 12), mnemo: "LDH (a8),A" } ),
	Some( Opcode { is_cb: false, value: 0xe1, ncycles: (12, 12), mnemo: "POP HL" } ),
	Some( Opcode { is_cb: false, value: 0xe2, ncycles: ( 8,  8), mnemo: "LD (C),A" } ),
	None, // 0xe3
	None, // 0xe4
	Some( Opcode { is_cb: false, value: 0xe5, ncycles: (16, 16), mnemo: "PUSH HL" } ),
	Some( Opcode { is_cb: false, value: 0xe6, ncycles: ( 8,  8), mnemo: "AND d8" } ),
	Some( Opcode { is_cb: false, value: 0xe7, ncycles: (16, 16), mnemo: "RST 20H" } ),
	Some( Opcode { is_cb: false, value: 0xe8, ncycles: (16, 16), mnemo: "ADD SP,r8" } ),
	Some( Opcode { is_cb: false, value: 0xe9, ncycles: ( 4,  4), mnemo: "JP (HL)" } ),
	Some( Opcode { is_cb: false, value: 0xea, ncycles: (16, 16), mnemo: "LD (a16),A" } ),
	None, // 0xeb
	None, // 0xec
	None, // 0xed
	Some( Opcode { is_cb: false, value: 0xee, ncycles: ( 8,  8), mnemo: "XOR d8" } ),
	Some( Opcode { is_cb: false, value: 0xef, ncycles: (16, 16), mnemo: "RST 28H" } ),
	Some( Opcode { is_cb: false, value: 0xf0, ncycles: (12, 12), mnemo: "LDH A,(a8)" } ),
	Some( Opcode { is_cb: false, value: 0xf1, ncycles: (12, 12), mnemo: "POP AF" } ),
	Some( Opcode { is_cb: false, value: 0xf2, ncycles: ( 8,  8), mnemo: "LD A,(C)" } ),
	Some( Opcode { is_cb: false, value: 0xf3, ncycles: ( 4,  4), mnemo: "DI" } ),
	None, // 0xf4
	Some( Opcode { is_cb: false, value: 0xf5, ncycles: (16, 16), mnemo: "PUSH AF" } ),
	Some( Opcode { is_cb: false, value: 0xf6, ncycles: ( 8,  8), mnemo: "OR d8" } ),
	Some( Opcode { is_cb: false, value: 0xf7, ncycles: (16, 16), mnemo: "RST 30H" } ),
	Some( Opcode { is_cb: false, value: 0xf8, ncycles: (12, 12), mnemo: "LD HL,SP+r8" } ),
	Some( Opcode { is_cb: false, value: 0xf9, ncycles: ( 8,  8), mnemo: "LD SP,HL" } ),
	Some( Opcode { is_cb: false, value: 0xfa, ncycles: (16, 16), mnemo: "LD A,(a16)" } ),
	Some( Opcode { is_cb: false, value: 0xfb, ncycles: ( 4,  4), mnemo: "EI" } ),
	None, // 0xfc
	None, // 0xfd
	Some( Opcode { is_cb: false, value: 0xfe, ncycles: ( 8,  8), mnemo: "CP d8" } ),
	Some( Opcode { is_cb: false, value: 0xff, ncycles: (16, 16), mnemo: "RST 38H" } ),
];

// Table that contains cb-prefixed opcodes.
pub const TABLE_CB_PREFIXED: [Option<Opcode>; 256] = [
	Some( Opcode { is_cb:  true, value: 0x00, ncycles: ( 8,  8), mnemo: "RLC B" } ),
	Some( Opcode { is_cb:  true, value: 0x01, ncycles: ( 8,  8), mnemo: "RLC C" } ),
	Some( Opcode { is_cb:  true, value: 0x02, ncycles: ( 8,  8), mnemo: "RLC D" } ),
	Some( Opcode { is_cb:  true, value: 0x03, ncycles: ( 8,  8), mnemo: "RLC E" } ),
	Some( Opcode { is_cb:  true, value: 0x04, ncycles: ( 8,  8), mnemo: "RLC H" } ),
	Some( Opcode { is_cb:  true, value: 0x05, ncycles: ( 8,  8), mnemo: "RLC L" } ),
	Some( Opcode { is_cb:  true, value: 0x06, ncycles: (16, 16), mnemo: "RLC (HL)" } ),
	Some( Opcode { is_cb:  true, value: 0x07, ncycles: ( 8,  8), mnemo: "RLC A" } ),
	Some( Opcode { is_cb:  true, value: 0x08, ncycles: ( 8,  8), mnemo: "RRC B" } ),
	Some( Opcode { is_cb:  true, value: 0x09, ncycles: ( 8,  8), mnemo: "RRC C" } ),
	Some( Opcode { is_cb:  true, value: 0x0a, ncycles: ( 8,  8), mnemo: "RRC D" } ),
	Some( Opcode { is_cb:  true, value: 0x0b, ncycles: ( 8,  8), mnemo: "RRC E" } ),
	Some( Opcode { is_cb:  true, value: 0x0c, ncycles: ( 8,  8), mnemo: "RRC H" } ),
	Some( Opcode { is_cb:  true, value: 0x0d, ncycles: ( 8,  8), mnemo: "RRC L" } ),
	Some( Opcode { is_cb:  true, value: 0x0e, ncycles: (16, 16), mnemo: "RRC (HL)" } ),
	Some( Opcode { is_cb:  true, value: 0x0f, ncycles: ( 8,  8), mnemo: "RRC A" } ),
	Some( Opcode { is_cb:  true, value: 0x10, ncycles: ( 8,  8), mnemo: "RL B" } ),
	Some( Opcode { is_cb:  true, value: 0x11, ncycles: ( 8,  8), mnemo: "RL C" } ),
	Some( Opcode { is_cb:  true, value: 0x12, ncycles: ( 8,  8), mnemo: "RL D" } ),
	Some( Opcode { is_cb:  true, value: 0x13, ncycles: ( 8,  8), mnemo: "RL E" } ),
	Some( Opcode { is_cb:  true, value: 0x14, ncycles: ( 8,  8), mnemo: "RL H" } ),
	Some( Opcode { is_cb:  true, value: 0x15, ncycles: ( 8,  8), mnemo: "RL L" } ),
	Some( Opcode { is_cb:  true, value: 0x16, ncycles: (16, 16), mnemo: "RL (HL)" } ),
	Some( Opcode { is_cb:  true, value: 0x17, ncycles: ( 8,  8), mnemo: "RL A" } ),
	Some( Opcode { is_cb:  true, value: 0x18, ncycles: ( 8,  8), mnemo: "RR B" } ),
	Some( Opcode { is_cb:  true, value: 0x19, ncycles: ( 8,  8), mnemo: "RR C" } ),
	Some( Opcode { is_cb:  true, value: 0x1a, ncycles: ( 8,  8), mnemo: "RR D" } ),
	Some( Opcode { is_cb:  true, value: 0x1b, ncycles: ( 8,  8), mnemo: "RR E" } ),
	Some( Opcode { is_cb:  true, value: 0x1c, ncycles: ( 8,  8), mnemo: "RR H" } ),
	Some( Opcode { is_cb:  true, value: 0x1d, ncycles: ( 8,  8), mnemo: "RR L" } ),
	Some( Opcode { is_cb:  true, value: 0x1e, ncycles: (16, 16), mnemo: "RR (HL)" } ),
	Some( Opcode { is_cb:  true, value: 0x1f, ncycles: ( 8,  8), mnemo: "RR A" } ),
	Some( Opcode { is_cb:  true, value: 0x20, ncycles: ( 8,  8), mnemo: "SLA B" } ),
	Some( Opcode { is_cb:  true, value: 0x21, ncycles: ( 8,  8), mnemo: "SLA C" } ),
	Some( Opcode { is_cb:  true, value: 0x22, ncycles: ( 8,  8), mnemo: "SLA D" } ),
	Some( Opcode { is_cb:  true, value: 0x23, ncycles: ( 8,  8), mnemo: "SLA E" } ),
	Some( Opcode { is_cb:  true, value: 0x24, ncycles: ( 8,  8), mnemo: "SLA H" } ),
	Some( Opcode { is_cb:  true, value: 0x25, ncycles: ( 8,  8), mnemo: "SLA L" } ),
	Some( Opcode { is_cb:  true, value: 0x26, ncycles: (16, 16), mnemo: "SLA (HL)" } ),
	Some( Opcode { is_cb:  true, value: 0x27, ncycles: ( 8,  8), mnemo: "SLA A" } ),
	Some( Opcode { is_cb:  true, value: 0x28, ncycles: ( 8,  8), mnemo: "SRA B" } ),
	Some( Opcode { is_cb:  true, value: 0x29, ncycles: ( 8,  8), mnemo: "SRA C" } ),
	Some( Opcode { is_cb:  true, value: 0x2a, ncycles: ( 8,  8), mnemo: "SRA D" } ),
	Some( Opcode { is_cb:  true, value: 0x2b, ncycles: ( 8,  8), mnemo: "SRA E" } ),
	Some( Opcode { is_cb:  true, value: 0x2c, ncycles: ( 8,  8), mnemo: "SRA H" } ),
	Some( Opcode { is_cb:  true, value: 0x2d, ncycles: ( 8,  8), mnemo: "SRA L" } ),
	Some( Opcode { is_cb:  true, value: 0x2e, ncycles: (16, 16), mnemo: "SRA (HL)" } ),
	Some( Opcode { is_cb:  true, value: 0x2f, ncycles: ( 8,  8), mnemo: "SRA A" } ),
	Some( Opcode { is_cb:  true, value: 0x30, ncycles: ( 8,  8), mnemo: "SWAP B" } ),
	Some( Opcode { is_cb:  true, value: 0x31, ncycles: ( 8,  8), mnemo: "SWAP C" } ),
	Some( Opcode { is_cb:  true, value: 0x32, ncycles: ( 8,  8), mnemo: "SWAP D" } ),
	Some( Opcode { is_cb:  true, value: 0x33, ncycles: ( 8,  8), mnemo: "SWAP E" } ),
	Some( Opcode { is_cb:  true, value: 0x34, ncycles: ( 8,  8), mnemo: "SWAP H" } ),
	Some( Opcode { is_cb:  true, value: 0x35, ncycles: ( 8,  8), mnemo: "SWAP L" } ),
	Some( Opcode { is_cb:  true, value: 0x36, ncycles: (16, 16), mnemo: "SWAP (HL)" } ),
	Some( Opcode { is_cb:  true, value: 0x37, ncycles: ( 8,  8), mnemo: "SWAP A" } ),
	Some( Opcode { is_cb:  true, value: 0x38, ncycles: ( 8,  8), mnemo: "SRL B" } ),
	Some( Opcode { is_cb:  true, value: 0x39, ncycles: ( 8,  8), mnemo: "SRL C" } ),
	Some( Opcode { is_cb:  true, value: 0x3a, ncycles: ( 8,  8), mnemo: "SRL D" } ),
	Some( Opcode { is_cb:  true, value: 0x3b, ncycles: ( 8,  8), mnemo: "SRL E" } ),
	Some( Opcode { is_cb:  true, value: 0x3c, ncycles: ( 8,  8), mnemo: "SRL H" } ),
	Some( Opcode { is_cb:  true, value: 0x3d, ncycles: ( 8,  8), mnemo: "SRL L" } ),
	Some( Opcode { is_cb:  true, value: 0x3e, ncycles: (16, 16), mnemo: "SRL (HL)" } ),
	Some( Opcode { is_cb:  true, value: 0x3f, ncycles: ( 8,  8), mnemo: "SRL A" } ),
	Some( Opcode { is_cb:  true, value: 0x40, ncycles: ( 8,  8), mnemo: "BIT 0,B" } ),
	Some( Opcode { is_cb:  true, value: 0x41, ncycles: ( 8,  8), mnemo: "BIT 0,C" } ),
	Some( Opcode { is_cb:  true, value: 0x42, ncycles: ( 8,  8), mnemo: "BIT 0,D" } ),
	Some( Opcode { is_cb:  true, value: 0x43, ncycles: ( 8,  8), mnemo: "BIT 0,E" } ),
	Some( Opcode { is_cb:  true, value: 0x44, ncycles: ( 8,  8), mnemo: "BIT 0,H" } ),
	Some( Opcode { is_cb:  true, value: 0x45, ncycles: ( 8,  8), mnemo: "BIT 0,L" } ),
	Some( Opcode { is_cb:  true, value: 0x46, ncycles: (16, 16), mnemo: "BIT 0,(HL)" } ),
	Some( Opcode { is_cb:  true, value: 0x47, ncycles: ( 8,  8), mnemo: "BIT 0,A" } ),
	Some( Opcode { is_cb:  true, value: 0x48, ncycles: ( 8,  8), mnemo: "BIT 1,B" } ),
	Some( Opcode { is_cb:  true, value: 0x49, ncycles: ( 8,  8), mnemo: "BIT 1,C" } ),
	Some( Opcode { is_cb:  true, value: 0x4a, ncycles: ( 8,  8), mnemo: "BIT 1,D" } ),
	Some( Opcode { is_cb:  true, value: 0x4b, ncycles: ( 8,  8), mnemo: "BIT 1,E" } ),
	Some( Opcode { is_cb:  true, value: 0x4c, ncycles: ( 8,  8), mnemo: "BIT 1,H" } ),
	Some( Opcode { is_cb:  true, value: 0x4d, ncycles: ( 8,  8), mnemo: "BIT 1,L" } ),
	Some( Opcode { is_cb:  true, value: 0x4e, ncycles: (16, 16), mnemo: "BIT 1,(HL)" } ),
	Some( Opcode { is_cb:  true, value: 0x4f, ncycles: ( 8,  8), mnemo: "BIT 1,A" } ),
	Some( Opcode { is_cb:  true, value: 0x50, ncycles: ( 8,  8), mnemo: "BIT 2,B" } ),
	Some( Opcode { is_cb:  true, value: 0x51, ncycles: ( 8,  8), mnemo: "BIT 2,C" } ),
	Some( Opcode { is_cb:  true, value: 0x52, ncycles: ( 8,  8), mnemo: "BIT 2,D" } ),
	Some( Opcode { is_cb:  true, value: 0x53, ncycles: ( 8,  8), mnemo: "BIT 2,E" } ),
	Some( Opcode { is_cb:  true, value: 0x54, ncycles: ( 8,  8), mnemo: "BIT 2,H" } ),
	Some( Opcode { is_cb:  true, value: 0x55, ncycles: ( 8,  8), mnemo: "BIT 2,L" } ),
	Some( Opcode { is_cb:  true, value: 0x56, ncycles: (16, 16), mnemo: "BIT 2,(HL)" } ),
	Some( Opcode { is_cb:  true, value: 0x57, ncycles: ( 8,  8), mnemo: "BIT 2,A" } ),
	Some( Opcode { is_cb:  true, value: 0x58, ncycles: ( 8,  8), mnemo: "BIT 3,B" } ),
	Some( Opcode { is_cb:  true, value: 0x59, ncycles: ( 8,  8), mnemo: "BIT 3,C" } ),
	Some( Opcode { is_cb:  true, value: 0x5a, ncycles: ( 8,  8), mnemo: "BIT 3,D" } ),
	Some( Opcode { is_cb:  true, value: 0x5b, ncycles: ( 8,  8), mnemo: "BIT 3,E" } ),
	Some( Opcode { is_cb:  true, value: 0x5c, ncycles: ( 8,  8), mnemo: "BIT 3,H" } ),
	Some( Opcode { is_cb:  true, value: 0x5d, ncycles: ( 8,  8), mnemo: "BIT 3,L" } ),
	Some( Opcode { is_cb:  true, value: 0x5e, ncycles: (16, 16), mnemo: "BIT 3,(HL)" } ),
	Some( Opcode { is_cb:  true, value: 0x5f, ncycles: ( 8,  8), mnemo: "BIT 3,A" } ),
	Some( Opcode { is_cb:  true, value: 0x60, ncycles: ( 8,  8), mnemo: "BIT 4,B" } ),
	Some( Opcode { is_cb:  true, value: 0x61, ncycles: ( 8,  8), mnemo: "BIT 4,C" } ),
	Some( Opcode { is_cb:  true, value: 0x62, ncycles: ( 8,  8), mnemo: "BIT 4,D" } ),
	Some( Opcode { is_cb:  true, value: 0x63, ncycles: ( 8,  8), mnemo: "BIT 4,E" } ),
	Some( Opcode { is_cb:  true, value: 0x64, ncycles: ( 8,  8), mnemo: "BIT 4,H" } ),
	Some( Opcode { is_cb:  true, value: 0x65, ncycles: ( 8,  8), mnemo: "BIT 4,L" } ),
	Some( Opcode { is_cb:  true, value: 0x66, ncycles: (16, 16), mnemo: "BIT 4,(HL)" } ),
	Some( Opcode { is_cb:  true, value: 0x67, ncycles: ( 8,  8), mnemo: "BIT 4,A" } ),
	Some( Opcode { is_cb:  true, value: 0x68, ncycles: ( 8,  8), mnemo: "BIT 5,B" } ),
	Some( Opcode { is_cb:  true, value: 0x69, ncycles: ( 8,  8), mnemo: "BIT 5,C" } ),
	Some( Opcode { is_cb:  true, value: 0x6a, ncycles: ( 8,  8), mnemo: "BIT 5,D" } ),
	Some( Opcode { is_cb:  true, value: 0x6b, ncycles: ( 8,  8), mnemo: "BIT 5,E" } ),
	Some( Opcode { is_cb:  true, value: 0x6c, ncycles: ( 8,  8), mnemo: "BIT 5,H" } ),
	Some( Opcode { is_cb:  true, value: 0x6d, ncycles: ( 8,  8), mnemo: "BIT 5,L" } ),
	Some( Opcode { is_cb:  true, value: 0x6e, ncycles: (16, 16), mnemo: "BIT 5,(HL)" } ),
	Some( Opcode { is_cb:  true, value: 0x6f, ncycles: ( 8,  8), mnemo: "BIT 5,A" } ),
	Some( Opcode { is_cb:  true, value: 0x70, ncycles: ( 8,  8), mnemo: "BIT 6,B" } ),
	Some( Opcode { is_cb:  true, value: 0x71, ncycles: ( 8,  8), mnemo: "BIT 6,C" } ),
	Some( Opcode { is_cb:  true, value: 0x72, ncycles: ( 8,  8), mnemo: "BIT 6,D" } ),
	Some( Opcode { is_cb:  true, value: 0x73, ncycles: ( 8,  8), mnemo: "BIT 6,E" } ),
	Some( Opcode { is_cb:  true, value: 0x74, ncycles: ( 8,  8), mnemo: "BIT 6,H" } ),
	Some( Opcode { is_cb:  true, value: 0x75, ncycles: ( 8,  8), mnemo: "BIT 6,L" } ),
	Some( Opcode { is_cb:  true, value: 0x76, ncycles: (16, 16), mnemo: "BIT 6,(HL)" } ),
	Some( Opcode { is_cb:  true, value: 0x77, ncycles: ( 8,  8), mnemo: "BIT 6,A" } ),
	Some( Opcode { is_cb:  true, value: 0x78, ncycles: ( 8,  8), mnemo: "BIT 7,B" } ),
	Some( Opcode { is_cb:  true, value: 0x79, ncycles: ( 8,  8), mnemo: "BIT 7,C" } ),
	Some( Opcode { is_cb:  true, value: 0x7a, ncycles: ( 8,  8), mnemo: "BIT 7,D" } ),
	Some( Opcode { is_cb:  true, value: 0x7b, ncycles: ( 8,  8), mnemo: "BIT 7,E" } ),
	Some( Opcode { is_cb:  true, value: 0x7c, ncycles: ( 8,  8), mnemo: "BIT 7,H" } ),
	Some( Opcode { is_cb:  true, value: 0x7d, ncycles: ( 8,  8), mnemo: "BIT 7,L" } ),
	Some( Opcode { is_cb:  true, value: 0x7e, ncycles: (16, 16), mnemo: "BIT 7,(HL)" } ),
	Some( Opcode { is_cb:  true, value: 0x7f, ncycles: ( 8,  8), mnemo: "BIT 7,A" } ),
	Some( Opcode { is_cb:  true, value: 0x80, ncycles: ( 8,  8), mnemo: "RES 0,B" } ),
	Some( Opcode { is_cb:  true, value: 0x81, ncycles: ( 8,  8), mnemo: "RES 0,C" } ),
	Some( Opcode { is_cb:  true, value: 0x82, ncycles: ( 8,  8), mnemo: "RES 0,D" } ),
	Some( Opcode { is_cb:  true, value: 0x83, ncycles: ( 8,  8), mnemo: "RES 0,E" } ),
	Some( Opcode { is_cb:  true, value: 0x84, ncycles: ( 8,  8), mnemo: "RES 0,H" } ),
	Some( Opcode { is_cb:  true, value: 0x85, ncycles: ( 8,  8), mnemo: "RES 0,L" } ),
	Some( Opcode { is_cb:  true, value: 0x86, ncycles: (16, 16), mnemo: "RES 0,(HL)" } ),
	Some( Opcode { is_cb:  true, value: 0x87, ncycles: ( 8,  8), mnemo: "RES 0,A" } ),
	Some( Opcode { is_cb:  true, value: 0x88, ncycles: ( 8,  8), mnemo: "RES 1,B" } ),
	Some( Opcode { is_cb:  true, value: 0x89, ncycles: ( 8,  8), mnemo: "RES 1,C" } ),
	Some( Opcode { is_cb:  true, value: 0x8a, ncycles: ( 8,  8), mnemo: "RES 1,D" } ),
	Some( Opcode { is_cb:  true, value: 0x8b, ncycles: ( 8,  8), mnemo: "RES 1,E" } ),
	Some( Opcode { is_cb:  true, value: 0x8c, ncycles: ( 8,  8), mnemo: "RES 1,H" } ),
	Some( Opcode { is_cb:  true, value: 0x8d, ncycles: ( 8,  8), mnemo: "RES 1,L" } ),
	Some( Opcode { is_cb:  true, value: 0x8e, ncycles: (16, 16), mnemo: "RES 1,(HL)" } ),
	Some( Opcode { is_cb:  true, value: 0x8f, ncycles: ( 8,  8), mnemo: "RES 1,A" } ),
	Some( Opcode { is_cb:  true, value: 0x90, ncycles: ( 8,  8), mnemo: "RES 2,B" } ),
	Some( Opcode { is_cb:  true, value: 0x91, ncycles: ( 8,  8), mnemo: "RES 2,C" } ),
	Some( Opcode { is_cb:  true, value: 0x92, ncycles: ( 8,  8), mnemo: "RES 2,D" } ),
	Some( Opcode { is_cb:  true, value: 0x93, ncycles: ( 8,  8), mnemo: "RES 2,E" } ),
	Some( Opcode { is_cb:  true, value: 0x94, ncycles: ( 8,  8), mnemo: "RES 2,H" } ),
	Some( Opcode { is_cb:  true, value: 0x95, ncycles: ( 8,  8), mnemo: "RES 2,L" } ),
	Some( Opcode { is_cb:  true, value: 0x96, ncycles: (16, 16), mnemo: "RES 2,(HL)" } ),
	Some( Opcode { is_cb:  true, value: 0x97, ncycles: ( 8,  8), mnemo: "RES 2,A" } ),
	Some( Opcode { is_cb:  true, value: 0x98, ncycles: ( 8,  8), mnemo: "RES 3,B" } ),
	Some( Opcode { is_cb:  true, value: 0x99, ncycles: ( 8,  8), mnemo: "RES 3,C" } ),
	Some( Opcode { is_cb:  true, value: 0x9a, ncycles: ( 8,  8), mnemo: "RES 3,D" } ),
	Some( Opcode { is_cb:  true, value: 0x9b, ncycles: ( 8,  8), mnemo: "RES 3,E" } ),
	Some( Opcode { is_cb:  true, value: 0x9c, ncycles: ( 8,  8), mnemo: "RES 3,H" } ),
	Some( Opcode { is_cb:  true, value: 0x9d, ncycles: ( 8,  8), mnemo: "RES 3,L" } ),
	Some( Opcode { is_cb:  true, value: 0x9e, ncycles: (16, 16), mnemo: "RES 3,(HL)" } ),
	Some( Opcode { is_cb:  true, value: 0x9f, ncycles: ( 8,  8), mnemo: "RES 3,A" } ),
	Some( Opcode { is_cb:  true, value: 0xa0, ncycles: ( 8,  8), mnemo: "RES 4,B" } ),
	Some( Opcode { is_cb:  true, value: 0xa1, ncycles: ( 8,  8), mnemo: "RES 4,C" } ),
	Some( Opcode { is_cb:  true, value: 0xa2, ncycles: ( 8,  8), mnemo: "RES 4,D" } ),
	Some( Opcode { is_cb:  true, value: 0xa3, ncycles: ( 8,  8), mnemo: "RES 4,E" } ),
	Some( Opcode { is_cb:  true, value: 0xa4, ncycles: ( 8,  8), mnemo: "RES 4,H" } ),
	Some( Opcode { is_cb:  true, value: 0xa5, ncycles: ( 8,  8), mnemo: "RES 4,L" } ),
	Some( Opcode { is_cb:  true, value: 0xa6, ncycles: (16, 16), mnemo: "RES 4,(HL)" } ),
	Some( Opcode { is_cb:  true, value: 0xa7, ncycles: ( 8,  8), mnemo: "RES 4,A" } ),
	Some( Opcode { is_cb:  true, value: 0xa8, ncycles: ( 8,  8), mnemo: "RES 5,B" } ),
	Some( Opcode { is_cb:  true, value: 0xa9, ncycles: ( 8,  8), mnemo: "RES 5,C" } ),
	Some( Opcode { is_cb:  true, value: 0xaa, ncycles: ( 8,  8), mnemo: "RES 5,D" } ),
	Some( Opcode { is_cb:  true, value: 0xab, ncycles: ( 8,  8), mnemo: "RES 5,E" } ),
	Some( Opcode { is_cb:  true, value: 0xac, ncycles: ( 8,  8), mnemo: "RES 5,H" } ),
	Some( Opcode { is_cb:  true, value: 0xad, ncycles: ( 8,  8), mnemo: "RES 5,L" } ),
	Some( Opcode { is_cb:  true, value: 0xae, ncycles: (16, 16), mnemo: "RES 5,(HL)" } ),
	Some( Opcode { is_cb:  true, value: 0xaf, ncycles: ( 8,  8), mnemo: "RES 5,A" } ),
	Some( Opcode { is_cb:  true, value: 0xb0, ncycles: ( 8,  8), mnemo: "RES 6,B" } ),
	Some( Opcode { is_cb:  true, value: 0xb1, ncycles: ( 8,  8), mnemo: "RES 6,C" } ),
	Some( Opcode { is_cb:  true, value: 0xb2, ncycles: ( 8,  8), mnemo: "RES 6,D" } ),
	Some( Opcode { is_cb:  true, value: 0xb3, ncycles: ( 8,  8), mnemo: "RES 6,E" } ),
	Some( Opcode { is_cb:  true, value: 0xb4, ncycles: ( 8,  8), mnemo: "RES 6,H" } ),
	Some( Opcode { is_cb:  true, value: 0xb5, ncycles: ( 8,  8), mnemo: "RES 6,L" } ),
	Some( Opcode { is_cb:  true, value: 0xb6, ncycles: (16, 16), mnemo: "RES 6,(HL)" } ),
	Some( Opcode { is_cb:  true, value: 0xb7, ncycles: ( 8,  8), mnemo: "RES 6,A" } ),
	Some( Opcode { is_cb:  true, value: 0xb8, ncycles: ( 8,  8), mnemo: "RES 7,B" } ),
	Some( Opcode { is_cb:  true, value: 0xb9, ncycles: ( 8,  8), mnemo: "RES 7,C" } ),
	Some( Opcode { is_cb:  true, value: 0xba, ncycles: ( 8,  8), mnemo: "RES 7,D" } ),
	Some( Opcode { is_cb:  true, value: 0xbb, ncycles: ( 8,  8), mnemo: "RES 7,E" } ),
	Some( Opcode { is_cb:  true, value: 0xbc, ncycles: ( 8,  8), mnemo: "RES 7,H" } ),
	Some( Opcode { is_cb:  true, value: 0xbd, ncycles: ( 8,  8), mnemo: "RES 7,L" } ),
	Some( Opcode { is_cb:  true, value: 0xbe, ncycles: (16, 16), mnemo: "RES 7,(HL)" } ),
	Some( Opcode { is_cb:  true, value: 0xbf, ncycles: ( 8,  8), mnemo: "RES 7,A" } ),
	Some( Opcode { is_cb:  true, value: 0xc0, ncycles: ( 8,  8), mnemo: "SET 0,B" } ),
	Some( Opcode { is_cb:  true, value: 0xc1, ncycles: ( 8,  8), mnemo: "SET 0,C" } ),
	Some( Opcode { is_cb:  true, value: 0xc2, ncycles: ( 8,  8), mnemo: "SET 0,D" } ),
	Some( Opcode { is_cb:  true, value: 0xc3, ncycles: ( 8,  8), mnemo: "SET 0,E" } ),
	Some( Opcode { is_cb:  true, value: 0xc4, ncycles: ( 8,  8), mnemo: "SET 0,H" } ),
	Some( Opcode { is_cb:  true, value: 0xc5, ncycles: ( 8,  8), mnemo: "SET 0,L" } ),
	Some( Opcode { is_cb:  true, value: 0xc6, ncycles: (16, 16), mnemo: "SET 0,(HL)" } ),
	Some( Opcode { is_cb:  true, value: 0xc7, ncycles: ( 8,  8), mnemo: "SET 0,A" } ),
	Some( Opcode { is_cb:  true, value: 0xc8, ncycles: ( 8,  8), mnemo: "SET 1,B" } ),
	Some( Opcode { is_cb:  true, value: 0xc9, ncycles: ( 8,  8), mnemo: "SET 1,C" } ),
	Some( Opcode { is_cb:  true, value: 0xca, ncycles: ( 8,  8), mnemo: "SET 1,D" } ),
	Some( Opcode { is_cb:  true, value: 0xcb, ncycles: ( 8,  8), mnemo: "SET 1,E" } ),
	Some( Opcode { is_cb:  true, value: 0xcc, ncycles: ( 8,  8), mnemo: "SET 1,H" } ),
	Some( Opcode { is_cb:  true, value: 0xcd, ncycles: ( 8,  8), mnemo: "SET 1,L" } ),
	Some( Opcode { is_cb:  true, value: 0xce, ncycles: (16, 16), mnemo: "SET 1,(HL)" } ),
	Some( Opcode { is_cb:  true, value: 0xcf, ncycles: ( 8,  8), mnemo: "SET 1,A" } ),
	Some( Opcode { is_cb:  true, value: 0xd0, ncycles: ( 8,  8), mnemo: "SET 2,B" } ),
	Some( Opcode { is_cb:  true, value: 0xd1, ncycles: ( 8,  8), mnemo: "SET 2,C" } ),
	Some( Opcode { is_cb:  true, value: 0xd2, ncycles: ( 8,  8), mnemo: "SET 2,D" } ),
	Some( Opcode { is_cb:  true, value: 0xd3, ncycles: ( 8,  8), mnemo: "SET 2,E" } ),
	Some( Opcode { is_cb:  true, value: 0xd4, ncycles: ( 8,  8), mnemo: "SET 2,H" } ),
	Some( Opcode { is_cb:  true, value: 0xd5, ncycles: ( 8,  8), mnemo: "SET 2,L" } ),
	Some( Opcode { is_cb:  true, value: 0xd6, ncycles: (16, 16), mnemo: "SET 2,(HL)" } ),
	Some( Opcode { is_cb:  true, value: 0xd7, ncycles: ( 8,  8), mnemo: "SET 2,A" } ),
	Some( Opcode { is_cb:  true, value: 0xd8, ncycles: ( 8,  8), mnemo: "SET 3,B" } ),
	Some( Opcode { is_cb:  true, value: 0xd9, ncycles: ( 8,  8), mnemo: "SET 3,C" } ),
	Some( Opcode { is_cb:  true, value: 0xda, ncycles: ( 8,  8), mnemo: "SET 3,D" } ),
	Some( Opcode { is_cb:  true, value: 0xdb, ncycles: ( 8,  8), mnemo: "SET 3,E" } ),
	Some( Opcode { is_cb:  true, value: 0xdc, ncycles: ( 8,  8), mnemo: "SET 3,H" } ),
	Some( Opcode { is_cb:  true, value: 0xdd, ncycles: ( 8,  8), mnemo: "SET 3,L" } ),
	Some( Opcode { is_cb:  true, value: 0xde, ncycles: (16, 16), mnemo: "SET 3,(HL)" } ),
	Some( Opcode { is_cb:  true, value: 0xdf, ncycles: ( 8,  8), mnemo: "SET 3,A" } ),
	Some( Opcode { is_cb:  true, value: 0xe0, ncycles: ( 8,  8), mnemo: "SET 4,B" } ),
	Some( Opcode { is_cb:  true, value: 0xe1, ncycles: ( 8,  8), mnemo: "SET 4,C" } ),
	Some( Opcode { is_cb:  true, value: 0xe2, ncycles: ( 8,  8), mnemo: "SET 4,D" } ),
	Some( Opcode { is_cb:  true, value: 0xe3, ncycles: ( 8,  8), mnemo: "SET 4,E" } ),
	Some( Opcode { is_cb:  true, value: 0xe4, ncycles: ( 8,  8), mnemo: "SET 4,H" } ),
	Some( Opcode { is_cb:  true, value: 0xe5, ncycles: ( 8,  8), mnemo: "SET 4,L" } ),
	Some( Opcode { is_cb:  true, value: 0xe6, ncycles: (16, 16), mnemo: "SET 4,(HL)" } ),
	Some( Opcode { is_cb:  true, value: 0xe7, ncycles: ( 8,  8), mnemo: "SET 4,A" } ),
	Some( Opcode { is_cb:  true, value: 0xe8, ncycles: ( 8,  8), mnemo: "SET 5,B" } ),
	Some( Opcode { is_cb:  true, value: 0xe9, ncycles: ( 8,  8), mnemo: "SET 5,C" } ),
	Some( Opcode { is_cb:  true, value: 0xea, ncycles: ( 8,  8), mnemo: "SET 5,D" } ),
	Some( Opcode { is_cb:  true, value: 0xeb, ncycles: ( 8,  8), mnemo: "SET 5,E" } ),
	Some( Opcode { is_cb:  true, value: 0xec, ncycles: ( 8,  8), mnemo: "SET 5,H" } ),
	Some( Opcode { is_cb:  true, value: 0xed, ncycles: ( 8,  8), mnemo: "SET 5,L" } ),
	Some( Opcode { is_cb:  true, value: 0xee, ncycles: (16, 16), mnemo: "SET 5,(HL)" } ),
	Some( Opcode { is_cb:  true, value: 0xef, ncycles: ( 8,  8), mnemo: "SET 5,A" } ),
	Some( Opcode { is_cb:  true, value: 0xf0, ncycles: ( 8,  8), mnemo: "SET 6,B" } ),
	Some( Opcode { is_cb:  true, value: 0xf1, ncycles: ( 8,  8), mnemo: "SET 6,C" } ),
	Some( Opcode { is_cb:  true, value: 0xf2, ncycles: ( 8,  8), mnemo: "SET 6,D" } ),
	Some( Opcode { is_cb:  true, value: 0xf3, ncycles: ( 8,  8), mnemo: "SET 6,E" } ),
	Some( Opcode { is_cb:  true, value: 0xf4, ncycles: ( 8,  8), mnemo: "SET 6,H" } ),
	Some( Opcode { is_cb:  true, value: 0xf5, ncycles: ( 8,  8), mnemo: "SET 6,L" } ),
	Some( Opcode { is_cb:  true, value: 0xf6, ncycles: (16, 16), mnemo: "SET 6,(HL)" } ),
	Some( Opcode { is_cb:  true, value: 0xf7, ncycles: ( 8,  8), mnemo: "SET 6,A" } ),
	Some( Opcode { is_cb:  true, value: 0xf8, ncycles: ( 8,  8), mnemo: "SET 7,B" } ),
	Some( Opcode { is_cb:  true, value: 0xf9, ncycles: ( 8,  8), mnemo: "SET 7,C" } ),
	Some( Opcode { is_cb:  true, value: 0xfa, ncycles: ( 8,  8), mnemo: "SET 7,D" } ),
	Some( Opcode { is_cb:  true, value: 0xfb, ncycles: ( 8,  8), mnemo: "SET 7,E" } ),
	Some( Opcode { is_cb:  true, value: 0xfc, ncycles: ( 8,  8), mnemo: "SET 7,H" } ),
	Some( Opcode { is_cb:  true, value: 0xfd, ncycles: ( 8,  8), mnemo: "SET 7,L" } ),
	Some( Opcode { is_cb:  true, value: 0xfe, ncycles: (16, 16), mnemo: "SET 7,(HL)" } ),
	Some( Opcode { is_cb:  true, value: 0xff, ncycles: ( 8,  8), mnemo: "SET 7,A" } ),
];

